### PR TITLE
Do not check for dependencies

### LINKED ISSUE #15: SeeShark fails due to missing postproc
Postproc library is GPL and is not included in some LGPL builds of FFmpeg libraries.
In SeeShark, FFmpegManager is checking the requested libraries, and all their dependencies. 
FFmpeg.Autogen defines postproc as a dependency of avfilter
Therefore, SeeShark effectively requires postproc. I think that postproc is kind of an optional dependency; it still runs if I comment out the checking of dependencies.

As a fix, you could simply not check the dependencies - just check the top-level libraries. Or, you could allow postproc to not be found without throwing an error.

### PR DESCRIPTION
**Pull request by Speykious**
Closes #15.

I hadn't read the code of `LoadLibrary` properly and assumed that dependencies were required as they were used during the loading process.
I was wrong, they are only being loaded with `n => LoadLibrary(libraryName: n, throwException: false)`, which means that if it fails to load it won't throw an exception.
https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/633c15d323785092561329ad4b5742b0189116d6/FFmpeg.AutoGen/FFmpeg.cs#L57-L82

Thus, it means that to be able to load a library you don't need to be able to load its dependencies.
Pretty simple fix in the end.

### CODE REVIEW

File: SeeShark/FFmpeg/FFmpegManager.cs [hunk 1]
```diff
@@ -118,7 +118,10 @@ public static bool CanLoadLibraries(LibraryFlags libraries = LibraryFlags.All, s
             return libraries.ToStrings().All((lib) => canLoadLibrary(lib, path, validated));
         }
 
-        // Note: recurses in a very similar way to the LoadLibrary() method.
+        // Note: dependencies are not checked as they are optional in FFmpeg.AutoGen.
```
Comment (sr229) [inline SeeShark/FFmpeg/FFmpegManager.cs:121]: Use XMLDoc here and put remarks instead. Would be better too.

**Review by sr229 — CHANGES_REQUESTED** [review]

File: SeeShark/FFmpeg/FFmpegManager.cs (hunk 1 above)
Comment (Speykious) [reply SeeShark/FFmpeg/FFmpegManager.cs]: Alright, done

**Review by sr229 — APPROVED** [review]
Intellisense-chan is happy
